
runenv: ""
externaldomain: ""

web:
  replicaCount: 2
  image: kreg.learn.entigo.io/hub/entigolabs/entigo-kubernetes-training-application:web-v1
  
api:
  replicaCount: 2
  image: kreg.learn.entigo.io/hub/entigolabs/entigo-kubernetes-training-application:api-v1
  redisHost: redis

redis:
  image: kreg.learn.entigo.io/hub/library/redis:6
